name: wooo
favicon: null
layout_spectrum: 0.27592
typography_spectrum: 0.4729688707739115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdbdb'
    - '#bea56c'
    - '#985e30'
    - '#77494c'
    - '#858378'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
