typography_spectrum: 0.4729688707739115
color:
  brandColors:
    - '#d7d7d7'
    - '#bfbfbf'
    - '#999999'
    - '#8a8a8a'
    - '#6a6a6a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.83823
analytics:
  google: null
  facebook: null
  twitter: null
name: wooo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: |+

purpose: []
