name: wooo
favicon: null
layout_spectrum: 0.27592
typography_spectrum: 0.4729688707739115
title: let is be a dairy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d7d7'
    - '#bfbfbf'
    - '#999999'
    - '#8a8a8a'
    - '#6a6a6a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
