name: wooo
favicon: null
layout_spectrum: 0.07784538390114903
typography_spectrum: 0.4729688707739115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbc2cc'
    - '#a4abb1'
    - '#efe1d8'
    - '#757b7e'
    - '#8e959d'
  brandStrength: 0.6875
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
